services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - ${HOME}/freshrss/data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - ${HOME}/freshrss/extensions:/var/www/FreshRSS/extensions
      - ${HOME}/freshrss/config:/config
    ports:
      # If you want to open a port 8080 on the local machine:
      - 8090:80
    environment:
      # A timezone http://php.net/timezones (default is UTC)
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
